# ==============================================================
# Trigger and  Feature Processing configuration 
# 
# 
# Syntax tip: NO TAB ALLOWED....
#   
#      If there is a tab you will get an error:
#      ScannerError: while scanning for the next token
#      found character '\t' that cannot start any token
#      in "./process_example.yaml", line 133, column 1
# 
#  VALIDATE with https://codebeautify.org/yaml-validator
# ==============================================================

# Filter file
filter_file: /data/users/serfass/run32/ofnxm_test/run32_test_filter.hdf5
didv_file: /path/to/didv_file.hdf5


# -------------------------------------------------
# SALTING
# -------------------------------------------------
salting:

   # DM PDF 
   dm_pdf_file: /path/to/pdf_file
   energies: [1,10,100]
   
   # 1x1
   Melange025pcRight:   
     template_tag: default
     noise_tag: default     
     collection_efficiency: 0.5
     dpdi_tag: default
     dpdi_poles: 2     

   # Using 2x2
   Melange025pcLeft|Melange025pcRight:
     template_tag: shared
     noise_tag: default     
     collection_efficiency: [0.4, 0.3]
     dpdi_tag: [default, default]
     dpdi_poles: [2, 2]
     
   # Using 3x1
   Melange4pc1ch|Melange025pcLeft|Melange025pcRight:
     template_tag: demo
     noise_tag: default     
     collection_efficiency: [0.5,0.4,0.3]
     dpdi_tag: [default, default, default]
     dpdi_poles: [2, 2, 2]
 

# -------------------------------------------------
# TRIGGER PROCESSING
# -------------------------------------------------
trigger:

   coincident_window_msec: 0.01
        
   Melange025pcLeft,Melange025pcRight:
       run: True
       template_tag: default
       psd_tag: default
       pileup_window_msec: 10
       threshold_sigma: 15


   Melange025pcLeft+Melange025pcRight:
       run: True
       trigger_name: TotIrPt
       template_tag: default
       psd_tag: default
       pileup_window_msec: 10
       threshold_sigma: 15




# -------------------------------------------------
# FEATURE PROCESSING 
# -------------------------------------------------

global:
    
    # trace/pretriggger length (continuous data)
    # (can be overwritten for each channel and
    # each channel's algorithms)
    #
    # use samples or msec ("_samples" or "_msec")
    
    trace_length_msec: 20
    pretrigger_length_msec: 10
  

# -------------------------------------------------
# Feature processing confuration for
# INDIVIDUAL channels
# -------------------------------------------------

# channels with fields are automatically enabled
# "all" field refer to all channels (settings can
# then overwritten in channel specific field)


# Settings for specific channels

Melange1pc1ch:
  
    of1x1_nodelay:
        run: True
        lowchi2_fcutoff: 50000
        template_tag: default

 
    of1x1_constrained:
        run: True
        window_min_from_trig_usec: -100
        window_max_from_trig_usec: 100
        lowchi2_fcutoff: 50000
        template_tag: default

    baseline:
        run: True
        window_min_from_start_usec: 0
        window_max_from_trig_usec: -2000

    baseline_end:   
        run: True
        base_algorithm: baseline
        window_min_from_trig_usec: 2000
        window_max_to_end_usec: 0

    maximum:
        run: True
        window_min_from_trig_usec: -500
        window_max_from_trig_usec: 500

    minimum:
        run: True
        window_min_from_trig_usec: -500
        window_max_from_trig_usec: 500
    
    energyabsorbed:
        run: False
        i0: 88e-9
        rl: 8.8e-3
        vb: 190.6e-9
        window_min_from_trig_usec: -100
        window_max_from_trig_usec: 1000
    
    integral:
        run: True
        window_min_from_trig_usec: -10
        window_max_from_trig_usec: 500
                
    psd_amp:
        run: True
        f_lims: [[45.0, 75.0], [300.0, 500.0], [350.0, 450.0], [150, 250], [250, 350]]


Melange025pcLeft,Melange025pcRight:
    
    of1x1_nodelay:
        run: True
        lowchi2_fcutoff: 50000
        template_tag: default

    of1x1_unconstrained:
        run: True
        template_tag: default

    of1x1_constrained:
        run: True
        window_min_from_trig_usec: -100
        window_max_from_trig_usec: 100
        lowchi2_fcutoff: 50000
        template_tag: default

    baseline:
        run: True
        window_min_from_start_usec: 0
        window_max_from_trig_usec: -2000

    baseline_end:   
        run: True
        base_algorithm: baseline
        window_min_from_trig_usec: 2000
        window_max_to_end_usec: 0

    maximum:
        run: True
        window_min_from_trig_usec: -500
        window_max_from_trig_usec: 500

    minimum:
        run: True
        window_min_from_trig_usec: -500
        window_max_from_trig_usec: 500
    
    energyabsorbed:
        run: False
        i0: 88e-9
        rl: 8.8e-3
        vb: 190.6e-9
        window_min_from_trig_usec: -100
        window_max_from_trig_usec: 1000
    
    integral:
        run: True
        window_min_from_trig_usec: -10
        window_max_from_trig_usec: 500
                
    psd_amp:
        run: True
        f_lims: [[45.0, 75.0], [300.0, 500.0], [350.0, 450.0], [150, 250], [250, 350]]



# -------------------------------------------------
# Feature processing channel combination
# (separator: +,-,|)
# -------------------------------------------------

Melange025pcLeft+Melange025pcRight:
    # feature channel
    feature_channel: Melange025pcSumLeftRight
   
    # weight (default = 1)
    weight_Melange025pcLeft: 0.9
    weight_Melange025pcRight: 1.1
    
    of1x1_constrained:
        run: True
        window_min_from_trig_usec: -100
        window_max_from_trig_usec: 100
        lowchi2_fcutoff: 50000
        template_tag: default

    baseline:
        run: True
        window_min_from_start_usec: 0
        window_max_from_trig_usec: -2000


Melange025pcLeft|Melange025pcRight:

     # channel rename
     feature_channel: Melange025pcLR

     of2x2_test1:
        run: True
        base_algorithm: ofnxm

        # amplitude names (default: amp1,amp2, amp3...)
        # need to match the number of templates
        amplitude_names: [amptest1, amptest2]

        # OF window
        window_min_from_trig_usec: -100
        window_max_from_trig_usec: 100

        # csd
        csd_tag: default

        # templates can be either
        # 
        #  1: templates for each channels
        #       Example 2x2:  template_tag_Melange1pc1ch: [default, None]
        # 
        #  2: array of tags (Nchans, Mtemps)
        #       Examples 2x2:   template_tag: [[default, None],[None, default]]	 
        #
        #  3: single tag if stored as (Nchan, Mtemps, samples) in filter file
        #       Example: template_tag: default
        #       
        # Use None if zeros

        template_tag_Melange025pcLeft: [single_025L, None]
        template_tag_Melange025pcRight: [None, single_025R]

        # cutoff NOT IMPLEMENTED IN QETpy
        lowchi2_fcutoff: 50000

     of2x2_test2:
        run: True
        base_algorithm: ofnxm

        # amplitude names
        #amplitude_names: [amp1, amp2]

        # OF window
        window_min_from_trig_usec: -100
        window_max_from_trig_usec: 100

        # csd
        csd_tag: default

        # template tags
        template_tag: [[default, None], [None, default]]

        # cutoff NOT IMPLEMENTED IN QETpy
        lowchi2_fcutoff: 50000


Melange4pc1ch|Melange025pcLeft|Melange025pcRight:

     # channel rename
     feature_channel: Melange4pc025pcLR

     of3x1_test1:
        run: True
        base_algorithm: ofnxm

        # amplitude names (default: amp1,amp2,...)
        # need to match the number of templates
        amplitude_names: amptest

        # OF window
        window_min_from_trig_usec: -100
        window_max_from_trig_usec: 100

        # csd tag (if not "default")
        csd_tag: default

        # template tags
        template_tag: demo

        # cutoff NOT IMPLEMENTED IN QETpy
        lowchi2_fcutoff: 50000

     of3x1_test3:
        run: True
        base_algorithm: ofnxm

        # amplitude names (default: amp1,amp2,...)
        #amplitude_names: amptest

        # OF window
        window_min_from_trig_usec: -100
        window_max_from_trig_usec: 100

        # csd tag (if not "default")
        csd_tag: default

        # template tags (Nchan, Mtemps) -> (3,1)
        template_tag: [[None],[shared],[shared]]

        # cutoff NOT IMPLEMENTED IN QETpy
        lowchi2_fcutoff: 50000

   
       
      