# ==============================================================
# Trigger Processing configuration example using UCB R20 data
# version: development
#
# 
# Syntax tip: NO TAB ALLOWED.... If tab you will get an error:
#      ScannerError: while scanning for the next token
#      found character '\t' that cannot start any token
#      in "./process_example.yaml", line 133, column 1
# ==============================================================

filter_file: ./filter_example.hdf5

# ---------------------------------------
# Trigger data 
# ---------------------------------------

trigger:

   coincident_window_msec: 10
   #coincident_window_samples: 2000


   CPDv21Ge:
       run: True
       template_tag: default
       psd_tag: default
       pileup_window_msec: 10
       threshold_sigma: 10
       #positive_pulses: True	
       
   IrPtTESSmall,IrPtTESBig:
       run: True
       template_tag: default
       psd_tag: default
       pileup_window_msec: 10
       threshold_sigma: 2

   IrPtTESSmall+IrPtTESBig:
       run: False
       trigger_name: TotIrPt
       template_tag: default
       psd_tag: default
       pileup_window_msec: 2
       threshold_sigma: 10


   IrPtTESSmall-IrPtTESBig:
       run: False
       trigger_name: SubIrPt
       template_tag: default
       psd_tag: default
       pileup_window_msec: 2
       threshold_sigma: 10


   IrPtTESSmall|IrPtTESBig:
       run: False
       template_tag: default
       psd_tag: default
       pileup_window_msec: 2
       threshold_sigma: 10
