# ==============================================================
#  Trigger and Feature Processing configuration 
# 
#
#  Syntax tip: NO TAB ALLOWED....
#      If there is a tab you will get an error:
#      ScannerError: while scanning for the next token
#      found character '\t' that cannot start any token
#      in "./process_example.yaml", line 133, column 1
# ==============================================================

filter_file: /data/lbl/mw_salt/run46_filter.hdf5
#didv_file: /home/michael/salting/run46tests/pylelab_run46_analysis/didvBOTHCHAN.hdf5

# -------------------------------------------------
# SALTING PROCESSING
# -------------------------------------------------
salting:

   # DM PDF 
   #dm_pdf_file: /home/michael/salting/detprocess/examples/mass_dict.pkl
   energies: [30]
   nsalt: 5000

   # Using 2x1
   Mv3025pcRegular:
       template_tag: default
       noise_tag: default     
       collection_efficiency: [0.4]
       dpdi_tag: default
       dpdi_poles: 3
# -------------------------------------------------
# TRIGGER PROCESSING
# -------------------------------------------------
trigger:

   coincident_window_msec: 0.01

   Mv3025pcRegular:
       run: True
       trigger_name: Mv3025pc
       template_tag: default
       noise_tag: default
       pileup_window_msec: 10
       threshold_sigma: 15

# -------------------------------------------------
# FEATURE PROCESSING 
# -------------------------------------------------

global:
    
    # trace/pretriggger length (continuous data)
    # (can be overwritten for each channel and
    # each channel's algorithms)
    #
    # use samples or msec ("_samples" or "_msec")
    
    trace_length_msec: 20
    pretrigger_length_msec: 10
  


# Settings for individual channels

Mv3025pcRegular:
  
    of1x1_nodelay:
        run: True
        lowchi2_fcutoff: 50000
        template_tag: default

    of1x1_unconstrained:
        run: True
        lowchi2_fcutoff: 50000

    of1x1_constrained:
        run: True
        window_min_from_trig_usec: -40
        window_max_from_trig_usec: 40
        lowchi2_fcutoff: 50000

    baseline:
        run: True
        window_min_from_start_usec: 0
        window_max_from_trig_usec: -2000

    baseline_end:   
        run: True
        base_algorithm: baseline
        window_min_from_trig_usec: 2000
        window_max_to_end_usec: 0

    maximum:
        run: True
        window_min_from_trig_usec: -500
        window_max_from_trig_usec: 500

    minimum:
        run: True
        window_min_from_trig_usec: -500
        window_max_from_trig_usec: 500
    
    integral:
        run: True
        window_min_from_trig_usec: -10
        window_max_from_trig_usec: 500

    energyabsorbed:
        run: True
        window_min_from_trig_usec: -400
        window_max_from_trig_usec: 400
        vb: 8.012827838827832e-06
        i0: 4.024891360047181e-07
        rl: 7.6e-03

    psd_amp:
        run: True
        f_lims: [[45.0, 75.0], [300.0, 500.0], [350.0, 450.0], [150, 250], [250, 350]]

# Settings for NxM channels
#Mv3025pcRegular|Mv3025pcBigFins:
#
#     # channel rename
 #    feature_channel: Mv3025pc
####     base_algorithm: ofnxm
#
 #       # OF window
 #       window_min_from_trig_usec: -100
  #      window_max_from_trig_usec: 100
#
#        # csd
 #       noise_tag: default
#
#        # template tags
 #       template_tag: shared_Mv3025pcRegular
#
 #       # cutoff NOT IMPLEMENTED IN QETpy
  #      lowchi2_fcutoff: 50000